### PR TITLE
fix: error creating a wallet on ios

### PR DESCRIPTION
**Pull request by Luigy08**
## Description
  - When try to create a new wallet on iOS thrwo error.

## Reason
  - The function loadWallet in RNWeb3.swift had an error when try to cast to data the keystore

## To test
  1. Go to menu.
  2. Click **Create Wallet**.
  3. Insert any name and any pin.
  4. Click **Create Wallet**.

## Expected
  - After of Click **Create Wallet** in the. home must to displayed the new wallet.

### CODE REVIEW

**Review by detroitpro — APPROVED** [review]
Do we need to bump the version and push to npm or can you use/install it local?

**Comment by Luigy08** [comment]
> Do we need to bump the version and push to npm or can you use/install it local?

We can use it locally, just we need to install the library with the path of the project and next link it.

- To install run: yarn add file:../akroma-react-native .
- To link it run: npx react-native link akroma-react-native.

**Comment by Luigy08** [comment]
> > > Do we need to bump the version and push to npm or can you use/install it local?
> > 
> > 
> > We can use it locally, just we need to install the library with the path of the project and next link it.
> > 
> > * To install run: yarn add file:../akroma-react-native .
> > * To link it run: npx react-native link akroma-react-native.
> 
> Can you add that to readme?

Sure, I'll add it in this PR

**Review by detroitpro — APPROVED** [review]

**Comment by detroitpro** [comment]
Great, merge when you are ready.

**Pull request merged**
